title: "Antoine Hochet"
name: "Antoine Hochet"
description: "Researcher in Physical Oceanography"
repository: "webs/ahochet.github.io"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
include:
   _pages

locale: "en-US"
timezone: "Europe/Paris"

url: "https://ahochet.github.io"
baseurl: ""

author:
  name   : "Antoine Hochet"
  avatar : "/assets/images/profile.jpg"
  bio    : |
       CPJ-CNRS <br>
       Laboratoire d’Océanographie Physique et Spatiale <br>
       LOPS UMR 6523 <br>
       IUEM D120 <br>
       Plouzané, France  
  email  : "antoine.hochet[at]univ-brest.fr"

markdown: kramdown
permalink: /:categories/:title/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true

plugins:
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag


